// Media base URL and helper functions
const BASE = 'https://cdn.jsdelivr.net/gh/calibancode/vinyl-media@7b93d4006ef14405c1b23cb103ff295ae87f46f6/';
const A = (f) => BASE + 'audio/' + f;
const IMG = (f) => BASE + 'art/' + f;
const FAV = (f) => BASE + 'fav/' + f;

// Track data
const tracks = [
  { title: "Shadow", artist: "Ernst Reijseger", src: A("shadow.opus"), art: IMG("shadow.webp"), blurb: "this song was sent to me by a friend who goes by kazimir. i don't think there was any context to it other than it sounding like a dying whale's journey through the light towards the other side. it's great. turns out it was made for a documentary about ancient humans called 'cave of forgotten dreams'. haven't seen it, but i have listened to the whole soundtrack and each one is a certified avant-banger." },
  { title: "Pagan Poetry", artist: "Björk", src: A("pagan-poetry.opus"), art: IMG("pagan-poetry.webp"), blurb: "i've liked björk long enough that i can't pin down what song really made her stick with me, but i like this one in particular for being all around björky goodness. look up the video of her fawning over a television, and then the one of her attacking a reporter." },
  { title: "Rats", artist: "Joy Again", src: A("rats.opus"), art: IMG("rats.webp"), blurb: "joy again was one of the few spotify algorithm drops that i actually enjoyed, let alone adored. despite listening to this song hundreds of times, i still can't really pin down what the fuck it means. it's like my version of seal's kiss from a rose. trying to understand what's happening isn't the point. that sick ass tune is the point. their other music is also good. the album this is from is called 'piano', and the art for it was a big push for me to make the album covers here visible. say 'thank you, rats'" },
  { title: "Black", artist: "Toby 'Radiation' Fox", src: A("black.opus"), art: IMG("black.webp"), blurb: "toby fox's 'black' is a song that needs no introduction. unless, of course, you aren't a terminally online young adult who grew up being read one of the most assinine webcomics in existence by your big siblings. this ear worm is, in a way, the 'theme' of bec noir's ascension to power, one of the major antagonists of homestuck with about as complex of moral reasoning as any other antagonist in homestuck. he's easily annoyed, and the answer to all his problems is, naturally, murder."},
  { title: "All Dead, All Dead", artist: "Queen", src: A("all-dead-all-dead.opus"), art: IMG("all-dead-all-dead.webp"), blurb: "one of my favorite songs from my favorite queen album. this one definitely shouldn't need any introduction. if you don't know who queen is, you're lying. if you know who queen is but haven't listened to their album 'news of the world', you should rectify that. this song is about brian may's late cat, believe it or not. that makes it sadder for me."},
  { title: "Equilibrium", artist: "Masayoshi Soken", src: A("equilibrium.opus"), art: IMG("equilibrium.webp"), blurb: "it was challenging to pick one raid song from ffxiv to share here. video game music doesn't usually have orchestral effort put into it, but soken goes unbelievably hard in a lot of the music made for this game. equilibrium just goes especially hard. i don't think you need to play ffxiv (and you probably shouldn't) in order to enjoy the breadth of music on display across it's expansions. soken is that much of a genius. i don't think he's phoned it in even once. even the goofiest tracks he's made for fourteen have soul you can't deny."},
  { title: "Fall Again (Demo)", artist: "Michael Jackson", src: A("fall-again.opus"), art: IMG("fall-again.webp"), blurb: "here's my pretentiously obscure mj pick for the setlist chosen entirely for exposure's sake, not because i necessarily sit down every morning and jerk off to the tear-wrenching heights of michael's weirdly precognizant lyrics. it's a good song, and it goes to show that the legend can be more than the thriller, though sometimes that never panned out. this demo track only surfaced in a box set for the mj ultimate collection in 2004, despite being recorded back in `99. rumor goes that life happened. sucks. you can't find this on streaming services, so i thought it'd be a neat addition." },
  { title: "Blue Lips", artist: "Regina Spektor", src: A("blue-lips.opus"), art: IMG("blue-lips.webp"), blurb: "blue lips was the first regina spektor song i ever heard, and i'm pretty sure it was a part of a homestuck animatic of some kind that i can't be arsed to look up, because regina's music went way beyond that little exposure moment for me. she became a favorite of mine as soon as i dove into her other albums. blue lips is nice, but it's nothing compared to the rest of her discography. regina is one of the few artists i've bothered to see live, and it was a unforgettable show. she was sick when she performed for us, hoarse voice and all that, but she sang so beautifully that you wouldn't have been able to tell, even despite having mentioned it. she played her best hits and some obscure ones, and even played us a demo she never intended to release because it was about how much she hated her neighbor or some shit. i love this lady to bits, and if there were any artist in this setlist i wholeheartedly suggest you check out, it would easily be regina spektor." },
  { title: "Goliath", artist: "Woodkid", src: A("goliath.opus"), art: IMG("goliath.webp"), blurb: "while this wasn't the first song i heard from woodkid (that would be 'so handsome hello'), it was by far the most impactful. it's one of the few tunes on this list impressive enough that even my music stingy partner can't help but adore. it hails from the album s16, woodkid's exploration into the human condition, our relationship with consumerism, and the destruction of the environment. it's a harsh album, very orchestral, and quite depressing, but damn is it fantastic. i probably would have put multiple songs from this album alone on this list if i wasn't trying to avoid bloating it unnecessarily. if there were one album on this setlist that i'd wholeheartedly suggest you check out, it would have to be s16."},
  { title: "Abbey", artist: "Mitski", src: A("abbey.opus"), art: IMG("abbey.webp"), blurb: "i can't claim to know what mitski's deal is since half her discography is about relationship loss, but i just hope she's doing alright. abbey is a prime example while not being so literally on the nose about it. apparently the fandom culture around her is incredibly toxic, but i don't have any first person experience with it. maybe, if you meet mitski on the street, don't grab and shake her like a bop-it."},
  { title: "1984 (西暦2000年に向けて)", artist: "Junko Yagami", src: A("1984.opus"), art: IMG("1984.webp"), blurb: "junko yagami's communication is an album from 1985 that, as i understand it, never saw that much critical acclaim. it was introduced to me by a friend who goes by exaccghost (they're also on neocities!) under circumstances i can't remember. it's a bop, that's all that matters. i highly recommend checking out the album since basically every song has something good to give. not into city pop? you're wrong. take an aspirin and try again." },
  { title: "Bones", artist: "Low Roar", src: A("bones.opus"), art: IMG("bones.webp"), blurb: "bones is one of the earlier songs that features in death stranding, kojima's parcel master babysitting simulator and my favorite video game of all time. it plays during an eight hour portion of the game that i'd consider the 'tutorial', where you're strapped for resources, vehicles, knowledge, and ability but forced to trudge through a post-apocalyptic wasteland because no one else will. when you feel like everything is lost and nothing matters, this game manages to sprinkle you with just enough hope to keep going in the form of tracks left by other players and downright banging music choices by kojimbo himself that play at just the right time. this addition is really more of a love letter to death stranding than it is to low roar. still, it's at least worth mentioning that low roar was a project of ryan karazija who passed in 2022. the project is a surviving and highly emotional element of him that's worth looking into." },
  { title: "Latin Simone", artist: "Gorillaz", src: A("latin-simone.opus"), art: IMG("latin-simone.webp"), blurb: "the g-sides version of latin simone is a lot more melancholy than its gorillaz debut album counterpart with vocals by ibrahim ferrer. the original english version feat. damon albarn, which i'm hosting here, feels more like a lonely downward spiral than a comforting friend. oddly enough, this track isn't even present on the european and japanese version of g-sides, so a lot of fans likely aren't even aware of its existence. i find that neat!" },
  { title: "Dark Red", artist: "Steve Lacy", src: A("dark-red.opus"), art: IMG("dark-red.webp"), blurb: "this is my suburban white boy pick. it's chill, groovy, and i listened to it way too many times while on my 30 minute drive to and from school every day as a teen. it's the only steve lacy song i know, too. i'd be called a fake fan if i ever claimed to be a fan, so i'm not gonna do that. i'm just a fan of this song in particular."},
  { title: "Ghosting", artist: "Mother Mother", src: A("ghosting.opus"), art: IMG("ghosting.webp"), blurb: "if you ever feel like you aren't good enough for your partner, at least you aren't dead. so, don't kill yourself! in all seriousness, mother mother is fairly well known and probably doesn't need much introduction. if you think you don't know them, look up 'hayloft' and i'm like 60% certain you'll say 'ohhh..' as for ghosting, i like it a lot more than hayloft, which is probably my, like.. top eight or nine in a twelve song album. i'm saying go listen to 'o my heart' in it's entirety." },
  { title: "Frozen Flame", artist: "Blank Banshee", src: A("frozen-flame.opus"), art: IMG("frozen-flame.webp"), blurb: "blank banshee is another recommendation from exaccghost which further proves their superior music taste to my own. they're the influential name in vaportrap. i don't think they've made a bad album, and this is just one nice song out of a whole discography of pretty unique music. at least, to my ears. maybe you hate this. maybe you hate me. that's your fault for making it this far and still thinking i have something coherent to offer you. everyone else can buckle up."},
  { title: "911 / Mr. Lonely (feat. Frank Ocean & Steve Lacy)", artist: "Tyler, The Creator", src: A("911.opus"), art: IMG("911.webp"), blurb: "dear diary, i'm 12 years old and this is deep. also, i lied earlier about only knowing one steve lacy song." },
  { title: "RADW", artist: "Haftbefehl", src: A("radw.opus"), art: IMG("radw.webp"), blurb: "this track was introduced to me by unitybirb, who probably thinks i'm gay for still listening to it rather than branching off into more interesting german rap territory. i don't speak german, but i do speak angst and bass. haftbefehl is apparently a really cool dude, despite rapping about drugs and gang activity like everyone else. if you like german rap at all, i'd recommend listening to more from him, but you probably already do. haftbefehl kind of reinvented the sound of the genre." },
  { title: "Wriggle", artist: "clipping.", src: A("wriggle.opus"), art: IMG("wriggle.webp"), blurb: "another artist introduced to me by unitybirb, firmly cementing them into a class above me in music taste. clipping was once described to me as sounding like 'the feeling you get when you drop your burnt toast buttered side down on the kitchen floor', and few songs in their discography convey that feeling better than wriggle."},
  { title: "Wolves", artist: "Kanye West", src: A("wolves.opus"), art: IMG("wolves.webp"), blurb: "this one definitely doesn't need an introduction. i can say that the life of pablo is one of my favorite kanye albums. this song in particular is fantastic. it even has sia! and, look, i know kanye isn't exactly kosher to associate with, and you'd be right if i cared."},
  { title: "DEAD FLOWERS", artist: "HEALTH, Poppy", src: A("dead-flowers.opus"), art: IMG("dead-flowers.webp"), blurb: "i'll admit it outright, this is my cheat song for getting two poppy songs in. but it's very good! health can make one hell of a dark, chunky beat which works way too well with poppy's angelic singing. i would love to see her live someday. more on poppy later." },
  { title: "Turn the Lights Off", artist: "Tally Hall", src: A("turn-the-lights-off.opus"), art: IMG("turn-the-lights-off.webp"), blurb: "this one is fun. not only was it my introduction to Tally Hall/Joe Hawley, but it was in the form of a frankly iconic fnaf animation by kibadoglover on youtube. just look up that artist's name and this song. honestly, there's a lot of other, better tally hall songs, but this one has a particularly special place in my heart for just how many god damn times i listened to it as a kid. obsession is a light word, and it's all kiba's fault."},
  { title: "Penelope Graves", artist: "Dirt Poor Robins", src: A("penelope-graves.opus"), art: IMG("penelope-graves.webp"), blurb: "this isn't the first dirt poor robins song i heard, that would be elanor rigby, but this one is an original. if you don't know dirt poor robins, they're a prog-rock band that blends orchestral, choral, and rock solos all in the same story albums. they're criminally underrated. you can find entire movies/stage plays they make to go along with their music on their youtube, and i recommend taking a look! you might just get lost in the sauce listening to 'babylon' and 'enchanté' over and over again for hours at a time." },
  { title: "Cheval", artist: "Igorrr", src: A("cheval.opus"), art: IMG("cheval.webp"), blurb: "let me say this straight. IGORRR FUCKS. honestly, i have mad respect for any artist, like igorrr, who will hire extremely talented individuals to play out their mad artistic whims without trying to take themselves too seriously. the end results are always fascinating, and more often than not, absolute bangers. the range of noises igorrr will show you throughout his discography could probably fill a book, but most of it revolves around what i and many others would call 'baroquecore' in its classically inspired insanity."},
  { title: "Computers", artist: "clown core", src: A("computers.opus"), art: IMG("computers.webp"), blurb: "in a similar vein to igorrr with a more narrow scope exists clowncore. these guys really take the 'not taking ourselves too seriously' aspect of the game to a whole 'nother level. i beg of you to watch the video series that was released along with the album this song is from, 'van'. i don't want to get hasty, but i think it'll change you. for the better? maybe. maybe not. are you fucking weak?" },
  { title: "MURDER EVERY 1 U KNOW!", artist: "femtanyl", src: A("murder-every-1-u-know.opus"), art: IMG("murder-every-1-u-know.webp"), blurb: "stream chaser." },
  { title: "Absolute Territory", artist: "Ken Ashcorp", src: A("absolute-territory.opus"), art: IMG("absolute-territory.webp"), blurb: "ken ashcorp is like if cringe incarnate learned how to use fl studio. me and most other people first heard his track 20 percent cooler back in the height of the brony days, and the rest of us stayed with his dumb ass for absolute territory. his music can be.. irreverent. but god damn, can that man commit to the bit." },
  { title: "Cheerleader", artist: "Ashnikko", src: A("cheerleader.opus"), art: IMG("cheerleader.webp"), blurb: "ashnikko is like if billie eilish had the balls to actually scare men away with her music. it's loud, brash, feminist, a little bit horny, and it really makes my ears happy. she hasn't made a bad album yet and i doubt she's ever going to." },
  { title: "HAZARD DUTY PAY!", artist: "JPEGMAFIA", src: A("hazard-duty-pay.opus"), art: IMG("hazard-duty-pay.webp"), blurb: "another introduction at fault of unitybirb. i don't really know what jpegmafia's deal is, but he can seriously produce. and produce he does, all on his own, from studio to release. that's kind of his whole schtick, being a capital S solo artist, no labels, no baggage, just really good music that i can't personally relate to anything else i've heard." },
  { title: "Touch Grass", artist: "Dorian Electra", src: A("touch-grass.opus"), art: IMG("touch-grass.webp"), blurb: "yet another unitybirb excursion! dorian electra hit hard for me from the first time i heard 'flamboyant' and 'career boy'. if regina spektor is my favorite singer-songwriter, dorian electra is my favorite pop star. god, now i'm imagining them in the same room together. that's giving me an aneurysm." },
  { title: "Rock Bottom Again", artist: "Pigeon John", src: A("rock-bottom-again.opus"), art: IMG("rock-bottom-again.webp"), blurb: "pigeon john is a weird one. he's mostly (almost exclusively) known for 'the bomb', which famously played in the 2014 e3 trailer for dead island 2 and in just about every single one of fighter pl's dark souls 3 pvp videos. but, maybe surprisingly, pigeon john has a discography. and it's actually some pretty good stuff!" },
  { title: "DEUS EX MACHINA", artist: "labirhin", src: A("deus-ex-machina.opus"), art: IMG("deus-ex-machina.webp"), blurb: "this is one of the newest songs on this playlist, and it's from a fantastic audio-visual artist from indonesia who goes by the handle labirhin. this song was composed to pair with the first episode of mau makan apa by the same name. the song is great, but the visuals and storytelling that are meant to go along with it really sell the experience in a way that i can't possibly hope to convey here. so.. go watch it already!"},
  { title: "The Holy Mountain", artist: "Poppy", src: A("the-holy-mountain.opus"), art: IMG("the-holy-mountain.webp"), blurb: "it's poppy! if you were around for her introduction as a strange meme figure but not for the subsequent musical career, you might be surprised to see the name again. hell, you probably forgot about the old meme, and that's probably for the best! i don't really know how to describe her other than giving me modern day david bowie vibes with her character driven music. i'm a big fan and i hope to see a lot more from her in the future."},
  { title: "CD Player, Pt. III", artist: "death's dynamic shroud", src: A("cd-player-pt-iii.opus"), art: IMG("cd-player-pt-iii.webp"), blurb: "another show-and-tell from exaccghost, and i distinctly remember first hearing these tunes in my absolutely bonkers tower unite house where we hung out for a few hours shooting the shit and listening to wacky beats. one such wacky beat comes from the musical ministrations of death's dynamic shroud, which i'm afraid to say i know woefully little about. what i do know is that this album, 'i'll try living like this', is widely considered to be a masterpiece in the vaporwave space. despite my middling understanding of the genre, i'd have to agree. the whole thing is a bop, through and through." },
  { title: "My Way", artist: "Frank Sinatra", src: A("my-way.opus"), art: IMG("my-way.webp"), blurb: "i'm italian. pizza gabagoolie salami calzone. frank sinatra hated this song, called it 'self serving and self indulgent'. seth macfarlane did a great rendition of this in the movie 'sing' where he plays as an asshole talking mouse." }
];

// About section data
const aboutData = {
  text: "i bevvy, ergo, i am. welcome to my site! i'm from the USA, and i was raised on Homestuck and FNAF. i like computers, and i enjoy making user-friendly foss programs. sometimes i do art, but good luck finding it!<br>the music you see above is a selection of songs that are meaningful to me for one reason or another, and i hope you enjoy them.",
  tags: [
    "pronouns: any/it ⚣",
    "intp-5w4",
    "arch btw",
    "masto: @bevvy@trollian.space",
    "signal: bevvy.04",
    "github: calibancode"
  ]
};

// Favorite images data
const favImages = [
  { src: FAV("rat-pizza.gif"), alt: "an animated rat feeding you pizza" },
  { src: FAV("my-summer-car-120.webp"), full: FAV("my-summer-car.webp"), alt: "a gif from my summer car of the player drinking beer and throwing the bottle at teimo" },
  { src: FAV("sad-imp.webp"), alt: "a sad looking imp in a fashionable wizard hat from homestuck" },
  { src: FAV("nightmare-blunt-rotation.webp"), alt: "hideo kojima smoking a fat dart" },
  { src: FAV("shady-sam.webp"), alt: "shady sam from oblivion with a massive red arrow pointing at his face" },
  { src: FAV("gucci-store.webp"), alt: "bladee buyin the gucci store its like breaching air its nothing it means nothing" },
  { src: FAV("nikola-einstein.webp"), alt: "charicatures of nikola and einstein" },
  { src: FAV("stolas-warzone.jpg"), alt: "now that you're gone stolas in the style of a shellshocked soldier" },
  { src: FAV("furry-abuse.jpg"), alt: "a classic furry meme depicting domestic abuse" },
  { src: FAV("shrek-avatar.jpg"), alt: "an unholy abomination depicting shrek as a na'vi from james cameron's avatar" },
  { src: FAV("wizard.webp"), alt: "an extremely powerful wizard" },
  { src: FAV("crusher-unicycle.jpg"), alt: "dr beverly crusher riding a motorcycle behind the scenes of star trek tng" },
  { src: FAV("mugshot.webp"), alt: "a baby spotted hyena looking faintly ridiculous" },
  { src: FAV("mood.jpg"), alt: "mituna captor and cronus ampora having a moment" },
  { src: FAV("car.png"), alt: "car from garn47 with soulless, dead eyes" },
  { src: FAV("timon.webp"), alt: "timon from the lion king with an unimpressed expression" }
];
